import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './favicon.ico'
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from '@/components/mode-toggle'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<html lang="en">
<link rel='x-icon' href='/favicon.ico'></link>
<body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <nav className='flex justify-between'>
          <h1 className='pl-4'>
            Milwaukee Weather
          </h1>
      <ModeToggle/>
        </nav>
        {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
